version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass      
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data      

volumes:
  pgdata:
